# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        exclude: ^alembic
        additional_dependencies: [
            "pydantic",
            "fastapi",
            "sqlmodel",
            "redis",
            "psycopg2-binary",
            "pymilvus",
            "celery-stubs"
        ]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --ignore=tests/worker/test_embeddings.py --ignore=tests/inference/test_inference_core.py
        language: system
        pass_filenames: false
        always_run: true
