services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: lainbow-api
    ports:
      - "${WEB_API_PORT:-8000}:8000"
    volumes:
      - ./src:/src
      - ./models:/src/models
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
