services:
  inference-api:
    build:
      context: .
      dockerfile: docker/inference.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: lainbow-inference-api
    ports:
      - "${INFERENCE_API_PORT:-8001}:8001"
    volumes:
      - ./src:/src
      - ./models:/src/models
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: ["uvicorn", "inference.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
